### ISSUE TITLE
version=1.0.0.qualifier in site.xml

### ISSUE THREAD

**Issue by rycee** [tobiasmelcher/EclipseAceJump#3]
In the [site.xml](https://tobiasmelcher.github.io/acejumpeclipse/site.xml) file on the update site it says the version is "1.0.0.qualifier". I think this is incorrect.

**Comment by tobiasmelcher** [comment]
Which value would be correct from your point of view?
The update site is currently build locally and then uploaded to github. Can you help in setting up a central/automatic build? Do you have experience in that area?

**Comment by rycee** [comment]
Sorry, I know next to nothing about Eclipse update sites. But from my limited understanding I would have expected "qualifier" in the `URL` and `version` attributes to be the date time string of the latest release. Specifically, instead of
```xml
<feature url="features/acejump.feature_1.0.0.qualifier.jar" id="acejump.feature" version="1.0.0.qualifier">
```
I would have expected, e.g.,
```xml
<feature url="features/acejump.feature_1.0.0.201610261941.jar" id="acejump.feature" version="1.0.0.201610261941">
```

My interest in this is that I am monitoring the `site.xml` for changes in order to track when I should update the [ace jump package](https://github.com/NixOS/nixpkgs/blob/98a9d815e05dd56aba0f9040d96092335cd90444/pkgs/applications/editors/eclipse/plugins.nix#L84) in the [NixOS](https://nixos.org) Linux distribution.

Oh, while I'm at it. It would be very nice if you could keep the JAR files from the old releases in the update site. That will help the package not break due to a 404 not found when a new ace jump release is made. Because I usually cannot immediately update the package in NixOS.

By the way, thanks for a very useful Eclipse plugin :smiley:

**Comment by tobiasmelcher** [comment]
I updated the site.xml and added the old jar files with change https://github.com/tobiasmelcher/tobiasmelcher.github.io/commit/3e8fe758e7f9f1d467dffff2b16f2bf4b4115e1e 

Will this be fine and work for you?

**Comment by rycee** [comment]
Yes, that is perfect. Many thanks!
