### ISSUE TITLE
Please support "jump any char", not just "beginning of the word"

### ISSUE THREAD

**Issue by 9527KGG** [tobiasmelcher/EclipseAceJump#4]
Currently, it only jumps to the "beginning of the word", not every convent.

If the word is long, eg,

abcdefghijklmnopqrstuvwxye

We've to jump to the 1st char. The manually go to the target char.

Thanks for helping. @tobiasmelcher

**Comment by tobiasmelcher** [comment]
Change 2051e001e8c008656636e28b6f60a27e70f66286 introduces a second command "aceJumpAnyChar" to jump to any char in the source. 
Warning: you have to assign a keyboard shortcut manually in the preferences, there is no default for the new command.
Could you please try it out? 
Thanks.

**Comment by 9527KGG** [comment]
I reinstalled "AceJump for Eclipse	1.0.0.202102071247"

I don't find the setting in preferences. May you please tell me which setting? Thanks.

**Comment by tobiasmelcher** [comment]
![image](https://user-images.githubusercontent.com/10373336/107193431-22fc6a80-69ef-11eb-9cde-904c17630f27.png)

I had to increase the minimum java requirements to JavaSE-9; otherwise the eclipse update site was not built with eclipse 2020-12.
Which eclipse and java version are you using?

**Comment by 9527KGG** [comment]
@tobiasmelcher , thanks. It works now.

But I see an issue. Currently, if there are more than 26 chars in the page, which is a common case, 
EclipseAceJump cannot find the occurrence after the 26 chars. 

May you please fix this issue?

As a comparison, in vim easymotion, for more than 26 occurrence, vim show ";a", ";b", ....

Thanks again.

**Comment by tobiasmelcher** [comment]
now implemented with ae22d24415d3b510148e123767021b60c3e791bf

could you please test?
Thanks.

**Comment by 9527KGG** [comment]
Great. It works now. Really appreciate your help.

May I ask one more suggestion?

**Currently:**
After 26 char, it becomes ,a ,b ,c ... ,z.

**Expectation:**
Follow vim easy motion. etc, after 26 char, it become ;a ;b ... ;z
Benefit: to type char ; you don't need move your finger, while to type char , you have to move your middle finger.

**Comment by 9527KGG** [comment]
Also I suggest map ctrl+; to "search any char" by default.

**Comment by tobiasmelcher** [comment]
done with ec705eebf79de8431f8eb423baa923e966916ea9

**Comment by kgfly** [comment]
It works now. Thanks for your help. Really appreciate.
